### ISSUE TITLE
Won't install from the app center.

### ISSUE THREAD

**Issue by christophersw** [davidmhewitt/clipped#10]
Howdy, 

After paying, and putting in my admin password, the install failed saying it was "not available". I am not seeing a way to re-trigger the install without re-paying... I did get the "thank you for your purchase" email, which directed me here to request help. Not sure if this is an issue with clipped, or with the app center, but any help would be appreciated. 

Thanks, 
Chris

**Comment by davidmhewitt** [comment]
Hello Chris,

Sorry you're experiencing these issues. I feel as though this is a temporary issue with AppCenter or something with your setup. Other people have installed Clipped from AppCenter without issues and no updates have been pushed for the application yet.

You should be able to re-attempt the installation by entering $0 as the custom payment amount in the drop down menu next to the buy button. As, AppCenter is a pay what you want store, it is perfectly reason to choose to pay nothing. Especially if you've already made a payment for that app :wink: 

Another thing to try would be a `sudo apt update` from the terminal just to check that the system's package manager is working properly and reports no errors.

Lastly, if you're still experiencing issues, you can report them on the AppCenter github page here: https://github.com/elementary/appcenter/issues

Let me know how it goes for you, and if you still can't manage to get Clipped instaled, let me know and I'll see what else I can do for you.

Thanks,
David

**Comment by christophersw** [comment]
This was entirely a problem on my end - when I reinstalled it worked perfectly. It hadn't occurred to me that I could just put in $0... Duh. 

Sorry for the bother, 
Chris

**Comment by davidmhewitt** [comment]
No worries. Thanks for the contributing to the project!

I hope it's useful for you and let me know if you come across any more issues.
