### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by orschiro** [davidmhewitt/clipped#23]
Just bought it using the App Center. :-)

What I am missing is support for images. 

Do you plan to add this?

**Comment by davidmhewitt** [comment]
Hey!

Thanks for your support. It's certainly something I plan to add, but I can't give a definite time when this would be implemented.

I already have an open issue for this, so I'll close this as a duplicate of #3.

**Comment by orschiro** [comment]
Wow great! Looking forward. Images are quite essential for me. Thanks for
your hard work. :)
