### ISSUE TITLE
Can't perform numeric search

### ISSUE THREAD

**Issue by firmantr3** [davidmhewitt/clipped#28]
How can i search clipboard history that are numeric when num keys [0-9] is bound to shortcut keys by default?

**Comment by davidmhewitt** [comment]
Fixed in 7ce781fa9bc2e36289c6b994fe611952dd829f86

This has been resolved by allowing numbers to be typed into the search bar when it is focused (after you start searching, or when you manually click in the search bar).

Typing a number when the search bar is not focused still uses it as a shortcut
