### ISSUE TITLE
Does not play well with arc-gtk theme

### ISSUE THREAD

**Issue by geraltofrivia** [davidmhewitt/clipped#34]
As shown in the screenshot below, the clipped UI becomes weird upon using the arc-gtk theme.

Its possible that the issue lies not with your implementation of the app, but rather with what the theme does to the UI, and if this is the case, I apologize. I intended to bring to light, if any, a bug that might have been caused due to your implementation.

![screenshot from 2018-12-07 18-55-49](https://user-images.githubusercontent.com/7823009/49664326-d6edbe00-fa51-11e8-8beb-d2fd298bc24c.png)

I'm using the arc theme current available via `apt install arc-theme` (as of 7th December, 2018).

Best,

**Comment by davidmhewitt** [comment]
Hello, I have fixed this in cd7f2f519c45816556f9c1bdb4d7cc0f4b346b4f by forcing Clipped to use the elementary theme if it is installed. I can't test Clipped against every theme to ensure it works properly.
