### ISSUE TITLE
The Shortcut to Open the App Should Close the App as Well Instead not ESC

### ISSUE THREAD

**Issue by worldofpeace** [davidmhewitt/clipped#7]
This behaviour would be typical of the elementary OS shortcut paradigm.

**Comment by davidmhewitt** [comment]
Thanks for the report.

Do you mean Ctrl+Q or Ctrl+W? 
Ctrl+Shift+V is an alternative paste shortcut is it not?

**Comment by worldofpeace** [comment]
I updated the issue title to clarify what I mean't.
:100:

**Comment by worldofpeace** [comment]
This would be nice in conjunction to when you unfocus the Dialog it closes.

**Comment by davidmhewitt** [comment]
That makes sense, thank you :slightly_smiling_face: 

I'll open a separate issue about closing on unfocus as that's slightly different.
