### ISSUE TITLE
Not Available on eOS 6.0 App Center

### ISSUE THREAD

**Issue by imreallyliam** [davidmhewitt/clipped#70]
Currently, this app isn't available on the eOS 6.0 app center, I'm going to build it to get the app working but just thought there should be an issue.

Update: Works 100% when built manually.

**Comment by davidmhewitt** [comment]
No curated applications are available on the elementary OS 6.0 AppCenter yet. This detailed on the page for the daily builds: https://builds.elementary.io/

This is not an issue with this project.
