### ISSUE TITLE
ElementaryOS

### ISSUE THREAD

**Issue by aliceemanueli** [davidmhewitt/clipped#76]
Good morning!  This app is not available in the ElementaryOS App Store... Please bring it to ElementaryOS.  Why do we miss it!

**Comment by davidmhewitt** [comment]
#73

**Comment by ayoungethan** [comment]
The way "clips" appears to do it (another clipboard manager in the AppCenter) is it just provides instructions about how to manually add the shortcuts via the system settings > keyboard > shortcuts > custom dialog, and it provides a direct link to that dialog.
