### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by jok3rsgr1n** [davidmhewitt/clipped#78]
i installed using this method...

git clone https://github.com/davidmhewitt/clipped
cd clipped
meson build --prefix=/usr
cd build
ninja
sudo ninja install

**Comment by eli-schwartz** [comment]
```
 sudo ninja uninstall
```

Should work.

**Comment by jok3rsgr1n** [comment]
Tried says no target

**Comment by jok3rsgr1n** [comment]
ninja: error: unknown target 'clipped'

**Comment by jok3rsgr1n** [comment]
got it thanks for the help i was doing it wrong lol
